version: '3.7'
services:
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  postgres_14:
    image: postgres:14
    environment:
      POSTGRES_DB: pulsar_manager
      POSTGRES_USER: pulsar
      POSTGRES_PASSWORD: c
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_14:/var/lib/postgresql/data

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    depends_on:
      - pulsar
      - postgres_14
    ports:
      - "9527:9527"
    environment:
      REDIRECT_HOST: localhost
      REDIRECT_PORT: 9527
      DRIVER_CLASS_NAME: org.postgresql.Driver
      URL: jdbc:postgresql://postgres:5432/pulsar_manager
      USERNAME: pulsar
      PASSWORD: pulsar
      LOG_LEVEL: DEBUG

volumes:
  postgres_data_14:
  clickhouse_data:
